subjects = [{"ACCT"},{"AEGD"},{"AERO"},{"AERS"},{"AFST"},{"AGCJ"},{"AGEC"},{"AGLS"},{"AGSC"},{"AGSM"},{"ALEC"},{"ALED"},{"ANSC"},{"ANTH"},{"ARAB"},{"ARCH"},{"ARTS"},{"ASCC"},{"ASIA"},{"ASTR"},{"ATMO"},{"ATTR"},{"BAEN",
"BEFB"},{"BESC"},{"BICH"},{"BIED"},{"BIMS"},{"BIOE"},{"BIOL"},{"BIOT"},{"BMEN"},{"BUAD"},{"BUSH"},{"BUSN"},{"CARC"},{"CEHD"},{"CHEM"},{"CHEN"},{"CHIN"},{"CLAS"},{"CLEN"},{"CLGE"},{"CLSC"},{"CLSL"},{"COMM",
"COMP"},{"COSC"},{"CPSY"},{"CSCE"},{"CVEN"},{"DASC"},{"DCED"},{"DDHS"},{"DPHS"},{"ECEN"},{"ECMT"},{"ECON"},{"EDAD"},{"EDCI"},{"EDHP"},{"EDTC"},{"EEBL"},{"EHRD"},{"ENDO"},{"ENDS"},{"ENGL"},{"ENGR"},{"ENTC"},{"ENTO"},{"EPFB",
"EPSY"},{"ESET"},{"ESSM"},{"EURO"},{"FILM"},{"FINC"},{"FIVS"},{"FREN"},{"FRSC"},{"FSTC"},{"GENE"},{"GEOG"},{"GEOL"},{"GEOP"},{"GEOS"},{"GERM"},{"GS01"},{"GS03"},{"GS04"},{"HCPI"},{"HEFB"},{"HHUM"},{"HISP",
"HIST"},{"HLTH"},{"HORT"},{"HPCH"},{"IBST"},{"IBUS"},{"ICPE"},{"IDIS"},{"INST"},{"INTA"},{"INTS"},{"ISEN"},{"ISTM"},{"ITAL"},{"ITDE"},{"JAPN"},{"JOUR"},{"KINE"},{"KNFB"},{"LAND"},{"LAW",
"LBAR"},{"LDEV"},{"LING"},{"MASC"},{"MATH"},{"MEEN"},{"MEFB"},{"MEID"},{"MEMA"},{"MEPS"},{"MGMT"},{"MKTG"},{"MLSC"},{"MMET"},{"MODL"},{"MPHY"},{"MPIM"},{"MSCI"},{"MSEN"},{"MUSC"},{"MXET",
"NEXT"},{"NFSC"},{"NRSC"},{"NUEN"},{"NURS"},{"NVSC"},{"OBIO"},{"OCEN"},{"OCNG"},{"OMFP"},{"OMFR"},{"OMFS"},{"ORTH"},{"PEDD"},{"PERF"},{"PERI"},{"PETE"},{"PHAR"},{"PHEB"},{"PHEO"},{"PHIL"},{"PHLT"},{"PHPM"},{"PHYS"},{"PLAN",
"PLPA"},{"POLS"},{"POSC"},{"PROS"},{"PSAA"},{"PSYC"},{"RDNG"},{"RELS"},{"RENR"},{"RPTS"},{"RUSS"},{"SABR"},{"SCEN"},{"SCMT"},{"SCSC"},{"SEFB"},{"SENG"},{"SOCI"},{"SOMS"},{"SOPH"},{"SPAN"},{"SPED"},{"SPMT"},{"SPSY"},{"STAT",
"TCMG"},{"TCMT"},{"TEED"},{"TEFB"},{"THAR"},{"UGST"},{"URPN"},{"URSC"},{"VIBS"},{"VIST"},{"VIZA"},{"VLCS"},{"VMID"},{"VPAT"},{"VSCS"},{"VTMI"},{"VTPB"},{"VTPP"},{"WFSC"},{"WGST"},{"WMHS"}]
